### ISSUE TITLE
Retrieving Merged Cluster

### ISSUE THREAD

**Issue by mdmanurung** [exaexa/shinyDendro#1]
First of all, thank you for the package!

Apologies for the naive question. Could you tell me how to retrieve vector of the merged cluster? I did not get anything after quitting the shiny application.

Best regards,
Mikhael

**Comment by exaexa** [comment]
Hello!

What exactly do you mean by 'vector of the merged cluster' ? The shiny app provides the shinyDendro input that contains the vector of assignments, if you need to take it out of the app, the best approach is to explicitly store it to a global variable. In particular, in the demo the vector is available here https://github.com/exaexa/shinyDendro/blob/master/test.R#L48-L50 ; there you can perfectly export it to a CSV, or save it to a global variable using something like
```r
someGlobalVar <<- input$sdClusters
```
Let me know if I understood the question correctly, or perhaps post some problematic code snippet so that we can work on it.

Best,
-mk

**Comment by mdmanurung** [comment]
That is exactly what I need! Thank you for your time.

Best regards,
Mikhael

**Comment by exaexa** [comment]
Great, thanks for confirmation!
